[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "python manage.py migrate --noinput"
startCommand = "gunicorn aflora_natural.wsgi --workers 2 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
