# Generated by Django 6.0.4 on 2026-04-27 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def _llenar_slugs(apps, schema_editor):
    """Genera slugs para Categoria y Producto que aun no tienen uno."""
    from django.utils.text import slugify
    Categoria = apps.get_model('catalogo', 'Categoria')
    Producto  = apps.get_model('catalogo', 'Producto')

    usados_cat = set(Categoria.objects.exclude(slug='').values_list('slug', flat=True))
    for c in Categoria.objects.filter(slug=''):
        base = slugify(c.nombre)[:120] or f'categoria-{c.pk}'
        s = base
        i = 2
        while s in usados_cat:
            s = f'{base}-{i}'
            i += 1
        c.slug = s
        c.save(update_fields=['slug'])
        usados_cat.add(s)

    usados_prod = set(Producto.objects.exclude(slug='').values_list('slug', flat=True))
    for p in Producto.objects.filter(slug=''):
        base = slugify(p.nombre)[:200] or f'producto-{p.pk}'
        s = base
        i = 2
        while s in usados_prod:
            s = f'{base}-{i}'
            i += 1
        p.slug = s
        p.save(update_fields=['slug'])
        usados_prod.add(s)




class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('alt', models.CharField(blank=True, help_text='Texto alternativo (accesibilidad y SEO)', max_length=160)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imagenes de producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('notificado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificacion de stock',
                'verbose_name_plural': 'Notificaciones de stock',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('comentario', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('aprobada', models.BooleanField(default=True, help_text='Moderacion: si False, no se muestra al publico.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Resena',
                'verbose_name_plural': 'Resenas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='SuscriptorNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscriptor newsletter',
                'verbose_name_plural': 'Suscriptores newsletter',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: '200g', 'Lavanda', 'Vainilla 100g'", max_length=120)),
                ('sku', models.CharField(blank=True, max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Variantes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado'], 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Menor = aparece primero'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Aparece en listados y meta description (SEO). Si vacio, se genera automatico.', max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Aparece en la home como destacado.'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Codigo interno opcional', max_length=40),
        ),
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, help_text='Si esta en falso, no aparece en el catalogo (oculto manualmente).'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal (tambien se muestra como primera de la galeria)', null=True, upload_to='productos/'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['disponible', 'categoria'], name='catalogo_pr_disponi_5ce3e2_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-creado'], name='catalogo_pr_creado_0f1965_idx'),
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='notificacionstock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_stock', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='resena',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variante',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_wishlist', to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notificacionstock',
            unique_together={('producto', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('producto', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('usuario', 'producto')},
        ),

        migrations.RunPython(
            code=_llenar_slugs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, db_index=True, max_length=220, unique=True),
        ),
    ]
