# Generated by Django 5.2.13 on 2026-04-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_imagenproducto_notificacionstock_resena_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('cuerpo', models.TextField(help_text='Texto plano. Las {variables} se reemplazan al enviar.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('enviada', 'Enviada'), ('error', 'Error')], default='borrador', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('total_destinatarios', models.PositiveIntegerField(default=0)),
                ('total_enviados', models.PositiveIntegerField(default=0)),
                ('total_fallidos', models.PositiveIntegerField(default=0)),
                ('nota_interna', models.TextField(blank=True, help_text='Nota privada solo visible en gestion')),
            ],
            options={
                'verbose_name': 'Campana de newsletter',
                'verbose_name_plural': 'Campanas de newsletter',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='suscriptornewsletter',
            name='token_baja',
            field=models.CharField(blank=True, db_index=True, help_text='Token unico para link de unsubscribe', max_length=40),
        ),
    ]
