# Generated by Django 6.0.4 on 2026-04-27 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_imagenproducto_notificacionstock_resena_and_more'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado'], 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nombre_snapshot',
            field=models.CharField(blank=True, help_text='Nombre del producto al momento de la compra', max_length=240),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.variante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='calle_numero',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_seguimiento',
            field=models.CharField(blank=True, help_text='Numero de seguimiento del courier', max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='depto',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(choices=[('envio_domicilio', 'Envio a domicilio'), ('retiro_local', 'Retiro en local')], default='envio_domicilio', max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nota_cliente',
            field=models.TextField(blank=True, help_text='Comentario opcional del cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='region',
            field=models.CharField(blank=True, default='Region Metropolitana', max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True, help_text='Legacy: direccion como texto. Nuevos pedidos usan campos estructurados.'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('preparando', 'Preparando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-creado'], name='pedidos_ped_creado_f50ddd_idx'),
        ),
    ]
