# Generated by Django 6.0.4 on 2026-04-27 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('catalogo', '0003_imagenproducto_notificacionstock_resena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrito',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.variante'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='sesion_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'variante')},
        ),
    ]
