# Generated by Django 6.0.4 on 2026-04-27 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(default='Casa', help_text='Ej: Casa, Trabajo', max_length=40)),
                ('nombre_destinatario', models.CharField(max_length=120)),
                ('calle_numero', models.CharField(help_text='Calle y numero', max_length=200)),
                ('depto', models.CharField(blank=True, help_text='Depto/oficina (opcional)', max_length=60)),
                ('comuna', models.CharField(max_length=80)),
                ('region', models.CharField(default='Region Metropolitana', max_length=80)),
                ('referencia', models.CharField(blank=True, help_text='Como llegar / referencia', max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('es_predeterminada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_predeterminada', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('recibir_newsletter', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
